### ISSUE TITLE
panic when deploying a "batch" job.

### ISSUE THREAD

**Issue by dansteen** [jrasell/levant#149]
Given the following job:

```
job "test" {
  datacenters = ["awse"]
  type = "batch"

  constraint {
    attribute = "${meta.role}"
    value     = "utility"
  }
  constraint {
    attribute = "${meta.env}"
    value     = "stag"
  }

  group "test" {

    # set our restart policy
    restart {
      interval = "1m"
      attempts = 2
      delay    = "15s"
      mode     = "fail"
    }
    count = 1

    task "test-batch" {
      artifact {
        source = "<some large file>"
      }
      leader = true
      driver = "exec"
      config {
        command = "bash"
        args = [ "-c", "sleep 30; true" ]
      }
      resources {
        cpu    = 100
        memory = 100
      }
    }

    task "test-service" {
      # grant access to secrets
      driver = "exec"
      config {
        command = "bash"
        args = [ "-c", "sleep infinity" ]
      }
      resources {
        cpu    = 100
        memory = 100
      }
    }
  }
}
```
I will occasionally get the following panic:

```
2018/04/20 17:08:40 EDT [INFO] levant/deploy: triggering a deployment of job test
2018/04/20 17:08:40 EDT [INFO] levant/deploy: evaluation 3ce2139c-0cd0-267d-e9a1-087ce0c30452 finished successfully
2018/04/20 17:08:41 EDT [INFO] levant/job_status_checker: job test has status running
2018/04/20 17:08:46 EDT [INFO] levant/job_status_checker: task test-service in allocation 146785f3-c531-f152-0493-4104f9e66328 has reached running state
2018/04/20 17:08:46 EDT [INFO] levant/job_status_checker: task test-batch in allocation 146785f3-c531-f152-0493-4104f9e66328 has reached running state
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/jrasell/levant/levant.allocationStatusChecker(0xc4200108a0, 0xc42045ce20, 0x1, 0x4, 0xc420125908)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/levant/job_status_checker.go:180 +0xe8
github.com/jrasell/levant/levant.(*levantDeployment).jobAllocationChecker(0xc4202ff3f0, 0xc4203baaa0, 0x4)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/levant/job_status_checker.go:107 +0x14c
github.com/jrasell/levant/levant.(*levantDeployment).jobStatusChecker(0xc4202ff3f0, 0xc4203baaa0, 0x0)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/levant/job_status_checker.go:34 +0x103
github.com/jrasell/levant/levant.(*levantDeployment).deploy(0xc4202ff3f0, 0xc4202ff3f0)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/levant/deploy.go:176 +0x9e7
github.com/jrasell/levant/levant.TriggerDeployment(0xc4201ee9c0, 0x2b)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/levant/deploy.go:66 +0xb7
github.com/jrasell/levant/command.(*DeployCommand).Run(0xc4202b9b60, 0xc42007c080, 0x1, 0x1, 0xc42000cfc0)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/command/deploy.go:125 +0x4ab
github.com/jrasell/levant/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc420203900, 0xc420203900, 0x4, 0xc42000d040)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.RunCustom(0xc42007c070, 0x2, 0x2, 0xc4202b99e0, 0xc4202b9920)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/main.go:49 +0x433
main.Run(0xc42007c070, 0x2, 0x2, 0xb5cdc8)
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/main.go:17 +0x56
main.main()
        /home/dsteen/projects/levant/src/github.com/jrasell/levant/main.go:11 +0x63

```

I only see this about once every 4th run, but the larger the artifact file the more likely it is to occur - which leads me to think this is some sort of race condition.

Thanks!

**Comment by dansteen** [comment]
Ok.  I figured out what is going on here.   The problem lies here:

https://github.com/jrasell/levant/blob/b6e80cdc585845296d3fc597c19174ab2835f065/levant/job_status_checker.go#L107

and here:
https://github.com/jrasell/levant/blob/b6e80cdc585845296d3fc597c19174ab2835f065/levant/job_status_checker.go#L176-L209

On line 107, the `allocationStatusChecker` function is run.  That function has allocation lists passed into it - the `levantTasks` map and the `allocs` object.   Inside the `allocationStatusChecker` function, the code loops through the `allocs` object, and allocations are deleted from the `levantTasks` map when they hit the running state.   Since a levantTasks is a map (a reference type), those changes are preserved from one run of the `allocationStatusChecker` function to the next.   

This is fine as long as all tasks in an allocation reach running in a single call to the `allocationStatusChecker`.  However, in the case where one task reaches running first, that task is removed from the `levantTasks` object.   Then the `allocationStatusChecker` exits, and runs again with a fresh copy of the `allocs` object, but ****the same copy of the `levantTasks` object that we removed a task from****.   

Then, the `allocationStatusChecker` function loops over the `allocs` object, and if it finds that the remaining task is running, it removes the task and, since there are no longer any tasks in that allocation, it removes the allocation itself from the `levantTasks` object.   However, the loop is still running (since it's looping over `allocs` not `levantTasks` and continues to try to access the allocation in the `levantTasks` object.  Since we have deleted it we get a panic.

The easiest fix I think is to not delete entries from `levantTasks`, but rather to mark them as "running".   I'll put together a patch for this.
