### ISSUE TITLE
[bug] panic when scaling out

### ISSUE THREAD

**Issue by jrasell** [jrasell/levant#251]
**Description**

```
Levant v0.2.5
Date: 2018-10-25T13:24:11Z
Commit: 0514741514e70caf82976c2c67f98414046b2392
Branch: 0.2.5
State: 0.2.5
Summary: 0514741514e70caf82976c2c67f98414046b2392
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x911661]

goroutine 1 [running]:
github.com/jrasell/levant/levant.(*levantDeployment).deploymentWatcher(0xc0002f0a20, 0xc0001b6060, 0x24, 0xc0001b6060)
	/home/travis/gopath/src/github.com/jrasell/levant/levant/deploy.go:279 +0x101
github.com/jrasell/levant/levant.(*levantDeployment).deploy(0xc0002f0a20, 0xc0001a8101)
	/home/travis/gopath/src/github.com/jrasell/levant/levant/deploy.go:167 +0x289
github.com/jrasell/levant/levant.TriggerDeployment(0xc000392f40, 0xc0001a81e0, 0x3a)
	/home/travis/gopath/src/github.com/jrasell/levant/levant/deploy.go:73 +0x77
github.com/jrasell/levant/scale.TriggerScalingEvent(0xc0001a8ae0, 0x4)
	/home/travis/gopath/src/github.com/jrasell/levant/scale/scale.go:43 +0x500
github.com/jrasell/levant/command.(*ScaleOutCommand).Run(0xc0001c3340, 0xc00001c070, 0x3, 0x3, 0xc0001c3080)
	/home/travis/gopath/src/github.com/jrasell/levant/command/scale_out.go:111 +0x407
github.com/jrasell/levant/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc0001e9a40, 0xc0001e9a40, 0x7, 0xc0001c30c0)
	/home/travis/gopath/src/github.com/jrasell/levant/vendor/github.com/mitchellh/cli/cli.go:255 +0x207
main.RunCustom(0xc00001c060, 0x4, 0x4, 0xc0002aba70, 0x0)
	/home/travis/gopath/src/github.com/jrasell/levant/main.go:62 +0x33c
main.Run(0xc00001c060, 0x4, 0x4, 0xc00008c058)
	/home/travis/gopath/src/github.com/jrasell/levant/main.go:30 +0x56
main.main()
	/home/travis/gopath/src/github.com/jrasell/levant/main.go:24 +0x15d
```

**Comment by stevenscg** [comment]
@jrasell I'm hitting this issue as well.

**Comment by numiralofe** [comment]
hi,

any build with this fix ?

tnks

**Comment by jrasell** [comment]
@numiralofe this is fixed in master; let me plan a release once I have fixed another bug I am currently working on.
