### ISSUE TITLE
Segvault

### ISSUE THREAD

**Issue by dropje86** [jrasell/levant#31]
With any version (0.0.1 or current master) I get this nil pointer.

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb36977]

goroutine 1 [running]:
github.com/jrasell/levant/levant.(*nomadClient).Deploy(0xc420089e60, 0xc4200b2d80, 0x0, 0xc420089e60)
	/var/lib/jenkins/jobs/levant/workspace/src/github.com/jrasell/levant/levant/deploy.go:63 +0x377
github.com/jrasell/levant/command.(*DeployCommand).Run(0xc42022be00, 0xc42008e060, 0x5, 0x5, 0xc420174f80)
	/var/lib/jenkins/jobs/levant/workspace/src/github.com/jrasell/levant/command/deploy.go:101 +0x524
github.com/jrasell/levant/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc420199680, 0xc420199680, 0x3, 0xc420174fe0)
	/var/lib/jenkins/jobs/levant/workspace/src/github.com/jrasell/levant/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.RunCustom(0xc42008e010, 0x6, 0x6, 0xc42022bcb0, 0xc42022bbf0)
	/var/lib/jenkins/jobs/levant/workspace/src/github.com/jrasell/levant/main.go:49 +0x433
main.Run(0xc42008e010, 0x6, 0x6, 0xb3cdf8)
	/var/lib/jenkins/jobs/levant/workspace/src/github.com/jrasell/levant/main.go:17 +0x56
main.main()
	/var/lib/jenkins/jobs/levant/workspace/src/github.com/jrasell/levant/main.go:11 +0x63
```

Problem is that `*job.Type` == `nil` because the Nomad job doesn't contain an explicit type, like so:
```
job "foobar" {
  type = "service"
}
```

This should be handled a bit more gracefully

**Comment by jrasell** [comment]
Thanks for the bug report @dropje86; it should indeed be handled correctly and I will have a fix for this shortly.

**Comment by dropje86** [comment]
Thanks James 👍  Took me a while to figure out why that was `nil` as the nomad default is `service`
